stages:
    - test
    - build_stage
    - deploy_stage

test_server:
    stage: test
    script:
        - pwd
        - ls
        - whoami
        - docker ps
        - docker ps -a
        - docker images
    tags:
        - public    


build:
    stage: build_stage
    script:
        - docker --version
        - docker build . -t vahtigenc/python-cicd:v$CI_PIPELINE_IID
    tags:
        - public


deploy:
    stage: deploy_stage
    script:
        - docker-compose up -d
    tags:
        - public

